window.C5DemoData = {
  viewerProfiles: [
    {
      name: 'Amina',
      goal: 'Build consistency',
      level: 'Beginner',
      preferredTime: 'Early mornings',
      gym: 'PureGym Canary Wharf',
      city: 'London, UK',
      gyms: [
        {
          name: 'PureGym Canary Wharf',
          distance: '0.6 mi',
          vibe: 'Best fit for early-morning structure before work',
          features: ['24/7 access', 'Strength floor', 'Functional rigs'],
          accent: 'linear-gradient(160deg, rgba(66,199,255,0.22), rgba(255,255,255,0.04))',
        },
        {
          name: 'Third Space City',
          distance: '1.3 mi',
          vibe: 'Premium environment with strong lunchtime traffic',
          features: ['Recovery zone', 'Studios', 'Free weights'],
          accent: 'linear-gradient(160deg, rgba(168,107,255,0.22), rgba(255,255,255,0.04))',
        },
        {
          name: 'Gymbox Bank',
          distance: '2.1 mi',
          vibe: 'High-energy option for motivated after-work sessions',
          features: ['Classes', 'Heavy lifting', 'Late evening access'],
          accent: 'linear-gradient(160deg, rgba(124,255,178,0.2), rgba(255,255,255,0.04))',
        },
      ],
      profiles: [
        {
          name: 'Jade',
          age: '24-29',
          goal: 'Stay accountable',
          gym: 'PureGym Canary Wharf',
          city: 'London, UK',
          score: 93,
          availableNow: true,
          note: 'Prefers 6:30 AM sessions before work and likes simple weekly check-ins.',
          gradient: 'linear-gradient(160deg, rgba(66,199,255,0.38), rgba(168,107,255,0.18))',
          initials: 'J',
        },
        {
          name: 'Noah',
          age: '30-34',
          goal: 'Build strength',
          gym: 'Third Space City',
          city: 'London, UK',
          score: 88,
          availableNow: false,
          note: 'Training for steady progression with weekday lunch lifts.',
          gradient: 'linear-gradient(160deg, rgba(124,255,178,0.24), rgba(66,199,255,0.20))',
          initials: 'N',
        },
        {
          name: 'Priya',
          age: '24-29',
          goal: 'Feel more confident',
          gym: 'Gymbox Bank',
          city: 'London, UK',
          score: 84,
          availableNow: true,
          note: 'Likes short, focused sessions and wants someone reliable for consistency.',
          gradient: 'linear-gradient(160deg, rgba(168,107,255,0.28), rgba(255,255,255,0.08))',
          initials: 'P',
        },
      ],
      matchReasons: [
        'Same city and early training window',
        'Shared accountability goal',
        'Overlapping gym routine and consistency target',
      ],
    },
    {
      name: 'Mateo',
      goal: 'Train harder',
      level: 'Intermediate',
      preferredTime: 'After work',
      gym: 'Smart Fit Reforma 222',
      city: 'Mexico City, Mexico',
      gyms: [
        {
          name: 'Smart Fit Reforma 222',
          distance: '0.5 mi',
          vibe: 'Best match for steady weekday evening sessions',
          features: ['Machines', 'Cardio zone', 'Extended hours'],
          accent: 'linear-gradient(160deg, rgba(66,199,255,0.22), rgba(255,255,255,0.04))',
        },
        {
          name: 'Sports World Condesa',
          distance: '1.4 mi',
          vibe: 'Balanced option with strong class energy',
          features: ['Studios', 'Weights', 'Recovery amenities'],
          accent: 'linear-gradient(160deg, rgba(168,107,255,0.22), rgba(255,255,255,0.04))',
        },
        {
          name: 'Station 24 Fitness Roma',
          distance: '2.2 mi',
          vibe: 'Flexible gym for late-night training blocks',
          features: ['24/7 access', 'Strength floor', 'Functional area'],
          accent: 'linear-gradient(160deg, rgba(124,255,178,0.2), rgba(255,255,255,0.04))',
        },
      ],
      profiles: [
        {
          name: 'Sofia',
          age: '25-30',
          goal: 'Get stronger',
          gym: 'Smart Fit Reforma 222',
          city: 'Mexico City, Mexico',
          score: 91,
          availableNow: true,
          note: 'Prefers weekday evening sessions and likes measurable weekly goals.',
          gradient: 'linear-gradient(160deg, rgba(66,199,255,0.38), rgba(168,107,255,0.18))',
          initials: 'S',
        },
        {
          name: 'Diego',
          age: '30-35',
          goal: 'Stay lean',
          gym: 'Sports World Condesa',
          city: 'Mexico City, Mexico',
          score: 86,
          availableNow: false,
          note: 'Mixes weights and cardio and wants a reliable post-work training partner.',
          gradient: 'linear-gradient(160deg, rgba(124,255,178,0.24), rgba(66,199,255,0.20))',
          initials: 'D',
        },
        {
          name: 'Valeria',
          age: '24-29',
          goal: 'Stay accountable',
          gym: 'Station 24 Fitness Roma',
          city: 'Mexico City, Mexico',
          score: 82,
          availableNow: true,
          note: 'Short sessions, high consistency, and quick check-ins work best for her.',
          gradient: 'linear-gradient(160deg, rgba(168,107,255,0.28), rgba(255,255,255,0.08))',
          initials: 'V',
        },
      ],
      matchReasons: [
        'Same city and after-work training window',
        'Compatible gym style and pace',
        'Shared goal around consistency and progression',
      ],
    },
    {
      name: 'Haruto',
      goal: 'Stay consistent',
      level: 'Advanced',
      preferredTime: 'Late evenings',
      gym: 'Anytime Fitness Shibuya',
      city: 'Tokyo, Japan',
      gyms: [
        {
          name: 'Anytime Fitness Shibuya',
          distance: '0.4 mi',
          vibe: 'Ideal for reliable late-evening training',
          features: ['24/7 access', 'Free weights', 'Compact cardio'],
          accent: 'linear-gradient(160deg, rgba(66,199,255,0.22), rgba(255,255,255,0.04))',
        },
        {
          name: 'Golds Gym Omotesando',
          distance: '1.1 mi',
          vibe: 'Best for serious lifting and structured splits',
          features: ['Heavy weights', 'Posing area', 'Classes'],
          accent: 'linear-gradient(160deg, rgba(168,107,255,0.22), rgba(255,255,255,0.04))',
        },
        {
          name: 'Konami Sports Club Ebisu',
          distance: '2.0 mi',
          vibe: 'Flexible gym with recovery options built in',
          features: ['Pool', 'Machines', 'Studios'],
          accent: 'linear-gradient(160deg, rgba(124,255,178,0.2), rgba(255,255,255,0.04))',
        },
      ],
      profiles: [
        {
          name: 'Emi',
          age: '24-29',
          goal: 'Train consistently',
          gym: 'Anytime Fitness Shibuya',
          city: 'Tokyo, Japan',
          score: 94,
          availableNow: true,
          note: 'Prefers late sessions after work and values low-drama accountability.',
          gradient: 'linear-gradient(160deg, rgba(66,199,255,0.38), rgba(168,107,255,0.18))',
          initials: 'E',
        },
        {
          name: 'Kenta',
          age: '30-34',
          goal: 'Build muscle',
          gym: 'Golds Gym Omotesando',
          city: 'Tokyo, Japan',
          score: 89,
          availableNow: false,
          note: 'Runs a structured split and likes partners who actually show up.',
          gradient: 'linear-gradient(160deg, rgba(124,255,178,0.24), rgba(66,199,255,0.20))',
          initials: 'K',
        },
        {
          name: 'Yui',
          age: '24-29',
          goal: 'Boost confidence',
          gym: 'Konami Sports Club Ebisu',
          city: 'Tokyo, Japan',
          score: 85,
          availableNow: true,
          note: 'Likes a mix of machines and classes with easy post-work check-ins.',
          gradient: 'linear-gradient(160deg, rgba(168,107,255,0.28), rgba(255,255,255,0.08))',
          initials: 'Y',
        },
      ],
      matchReasons: [
        'Same city and late-evening rhythm',
        'Shared consistency mindset',
        'Similar primary gym and training style',
      ],
    },
    {
      name: 'Zuri',
      goal: 'Build confidence',
      level: 'Beginner',
      preferredTime: 'Weekend mornings',
      gym: 'Virgin Active Sandton',
      city: 'Johannesburg, South Africa',
      gyms: [
        {
          name: 'Virgin Active Sandton',
          distance: '0.7 mi',
          vibe: 'Best fit for supportive beginner-friendly sessions',
          features: ['Studios', 'Cardio floor', 'Strength zone'],
          accent: 'linear-gradient(160deg, rgba(66,199,255,0.22), rgba(255,255,255,0.04))',
        },
        {
          name: 'Planet Fitness Rosebank',
          distance: '1.5 mi',
          vibe: 'Good balance of energy and accessibility',
          features: ['Machines', 'Weights', 'Extended hours'],
          accent: 'linear-gradient(160deg, rgba(168,107,255,0.22), rgba(255,255,255,0.04))',
        },
        {
          name: 'Ignite Fitness Melrose Arch',
          distance: '2.3 mi',
          vibe: 'Modern space for more focused progression',
          features: ['HIIT space', 'Free weights', 'Recovery lounge'],
          accent: 'linear-gradient(160deg, rgba(124,255,178,0.2), rgba(255,255,255,0.04))',
        },
      ],
      profiles: [
        {
          name: 'Lebo',
          age: '24-29',
          goal: 'Feel more confident',
          gym: 'Virgin Active Sandton',
          city: 'Johannesburg, South Africa',
          score: 92,
          availableNow: true,
          note: 'Likes weekend sessions and wants a steady accountability partner.',
          gradient: 'linear-gradient(160deg, rgba(66,199,255,0.38), rgba(168,107,255,0.18))',
          initials: 'L',
        },
        {
          name: 'Tumi',
          age: '30-34',
          goal: 'Stay active',
          gym: 'Planet Fitness Rosebank',
          city: 'Johannesburg, South Africa',
          score: 87,
          availableNow: false,
          note: 'Wants a realistic routine that still feels social and motivating.',
          gradient: 'linear-gradient(160deg, rgba(124,255,178,0.24), rgba(66,199,255,0.20))',
          initials: 'T',
        },
        {
          name: 'Aya',
          age: '24-29',
          goal: 'Get stronger',
          gym: 'Ignite Fitness Melrose Arch',
          city: 'Johannesburg, South Africa',
          score: 83,
          availableNow: true,
          note: 'Looking for someone consistent who keeps workouts simple and repeatable.',
          gradient: 'linear-gradient(160deg, rgba(168,107,255,0.28), rgba(255,255,255,0.08))',
          initials: 'A',
        },
      ],
      matchReasons: [
        'Same city and weekend training preference',
        'Shared confidence-building goal',
        'Compatible gym routine and accountability pace',
      ],
    },
  ],
  starterMessages: [
    { from: 'them', text: 'Hey! I usually train around this time. Want to lock in a session soon?' },
    { from: 'me', text: 'That works for me. I am trying to get more consistent this month.' },
    { from: 'them', text: 'Perfect. Let\'s keep it simple and make sure we both show up.' },
  ],
  quickReplies: [
    'Want to train tomorrow?',
    'What gym are you at this week?',
    'I can do a quick session after work',
  ],
  progress: {
    weekPoints: 18,
    daysLogged: 5,
    level: 'Beginner',
    nextLevel: 'Intermediate',
    chart: [
      { day: 'M', value: 3 },
      { day: 'T', value: 5 },
      { day: 'W', value: 0 },
      { day: 'T', value: 4 },
      { day: 'F', value: 6 },
      { day: 'S', value: 2 },
      { day: 'S', value: 4 },
    ],
    tasks: [
      'Protect your workout window',
      'Check in after your session',
      'Prep tomorrow before bed',
    ],
  },
};
