window.C5DemoData = {
  viewer: {
    name: 'Nathan',
    goal: 'Get consistent',
    level: 'Beginner',
    preferredTime: 'Mornings',
    gym: 'Crunch - Tampa',
    city: 'Tampa, FL',
  },
  profiles: [
    {
      name: 'Jordan',
      age: '24-29',
      goal: 'Get consistent',
      gym: 'Crunch - Tampa',
      city: 'Tampa, FL',
      score: 92,
      availableNow: true,
      note: 'Works out before class and wants an accountability partner for 6 AM sessions.',
      gradient: 'linear-gradient(160deg, rgba(66,199,255,0.38), rgba(168,107,255,0.18))',
      initials: 'J',
    },
    {
      name: 'Taylor',
      age: '30-34',
      goal: 'Build muscle',
      gym: 'EOS - Tampa',
      city: 'Tampa, FL',
      score: 87,
      availableNow: false,
      note: 'Looking for a steady split and someone reliable for weeknight training.',
      gradient: 'linear-gradient(160deg, rgba(124,255,178,0.24), rgba(66,199,255,0.20))',
      initials: 'T',
    },
    {
      name: 'Morgan',
      age: '24-29',
      goal: 'Boost confidence',
      gym: 'Amped Fitness - Tampa',
      city: 'Tampa, FL',
      score: 83,
      availableNow: true,
      note: 'Prefers short but consistent workouts and quick check-ins after every session.',
      gradient: 'linear-gradient(160deg, rgba(168,107,255,0.28), rgba(255,255,255,0.08))',
      initials: 'M',
    },
  ],
  matchReasons: [
    'Same city and training window',
    'Shared accountability goal',
    'Similar gym routine and consistency target',
  ],
  starterMessages: [
    { from: 'them', text: 'Hey! I usually train around 7 AM. Want to try a session tomorrow?' },
    { from: 'me', text: 'That works for me. I am trying to get more consistent this month.' },
    { from: 'them', text: 'Perfect. Let’s start with a quick upper-body workout and keep it simple.' },
  ],
  quickReplies: [
    'Want to train tomorrow at 7?',
    'Leg day this week?',
    'I’m at Crunch now',
  ],
  progress: {
    weekPoints: 18,
    daysLogged: 5,
    level: 'Beginner',
    nextLevel: 'Intermediate',
    chart: [
      { day: 'M', value: 3 },
      { day: 'T', value: 5 },
      { day: 'W', value: 0 },
      { day: 'T', value: 4 },
      { day: 'F', value: 6 },
      { day: 'S', value: 2 },
      { day: 'S', value: 4 },
    ],
    tasks: [
      'Protect your workout window',
      'Check in after your session',
      'Prep tomorrow before bed',
    ],
  },
};
